### ISSUE TITLE
Color functions

### ISSUE THREAD

**Issue by musjj** [SenchoPens/base16.nix#10]
Functions to lighten/darken/hue-shift/etc. colors would be really useful. Sometimes the palette isn't quite enough, so the ability to derive extra colors is always nice to have.

**Comment by SenchoPens** [comment]
Hi @musjj, thank you for this suggestion, but IMO this is out of scope for this library. I think for base16 / base24 / tinted-theming scheme tweaking an implementation-independent interactive tool would be best. This library is mostly just a nix implementation of standarts.
