### ISSUE TITLE
Integration with tinted-theming schemes

### ISSUE THREAD

**Issue by belak** [SenchoPens/base16.nix#12]
Hello! What would need to be done to support the scheme format we're moving to in https://github.com/tinted-theming/schemes? I would even be open to exporting something as a flake from the repo, if that would help, though I'm relatively new to nix, so advice would be appreciated.

**Comment by SenchoPens** [comment]
Hi @belak, base16.nix and Stylix already support the new format :)

**Comment by belak** [comment]
Oh, that's awesome. Thanks for the info!
