### ISSUE TITLE
base16 with gtk theme

### ISSUE THREAD

**Issue by Steven-S1020** [SenchoPens/base16.nix#14]
Hi,
I don't know if this has been done yet but I want to connect your base16 with my gtk theme. I see 'tinted-theming/base16-gtk-flatcolor' is a template, and I have tried using that, and either it needs to be done a special way, or it's not possible at this time. Below I will paste my theming.nix for reference. Any help or examples would be greatly appreciated.
Thanks!

theming.nix

```
{ config, pkgs, inputs, ...}:

{
  home-manager.users.steven = {

  
    # Theme 'alacritty'
    programs.alacritty.settings.colors = 
      with config.scheme.withHashtag; let default = {
        black = base00; white = base05;
        inherit red green yellow blue cyan magenta;  
      };
    in {
      primary = { background = base00; foreground = base05; };
      cursor = { text = base02; cursor = base07; };
      normal = default; bright = default; dim = default;
    };

    # Theme 'neovim'
    programs.neovim = {
      plugins = [ (pkgs.vimPlugins.base16-vim.overrideAttrs (old:
        let schemeFile = config.scheme inputs.base16-vim;
        in { patchPhase = "cp ${schemeFile} colors/base16-scheme.vim"; }
      ))];
      extraConfig = "
        set termguicolors background=dark
        let base16colorspace=256
        colorscheme base16-scheme
      ";  
    };

    # Theme 'gtk'
    gtk = builtins.readFile (config.scheme {
      templateRepo = inputs.base16-gtk; target = "gtk-3";
    });
  };
}
```

**Comment by SenchoPens** [comment]
Hi, sorry for replying late, I'm currently pretty busy. I haven't themed GTK myself. Have you checked out danth/stylix? It uses base16.nix under the hood and you can use your base16.nix scheme to theme GTK through it.

**Comment by SenchoPens** [comment]
Closed tue to innactivity, please reopen if the issue is still there after upgrade
