### ISSUE TITLE
YAML parsing fails with latest tinted-theming/tinted-foot

### ISSUE THREAD

**Issue by nazarewk** [SenchoPens/base16.nix#15]
cross-posting from https://github.com/tinted-theming/tinted-foot/issues/8 since I cannot create the issue directly inside https://github.com/SenchoPens/fromYaml

**Comment by SenchoPens** [comment]
I'm sorry, tinted-foot works on my machine. Please check that stylix is using the latest version of base16.nix. You can also enable IFD, see https://github.com/SenchoPens/base16.nix/tree/main#%EF%B8%8F-troubleshooting

**Comment by SenchoPens** [comment]
Closed due to innactivity, please reopen if the issue is still there after an update
