### ISSUE TITLE
Parsing is broken after recent tinted-theming changes

### ISSUE THREAD

**Issue by kurnevsky** [SenchoPens/base16.nix#17]
It seems this one broke it: https://github.com/tinted-theming/schemes/pull/34

**Comment by SenchoPens** [comment]
Fixed, please try it if you have time.

**Comment by bassforce86** [comment]
i've bumped this locally (I used this via stylix, so i've updated it's input to latest main for here) and it's working correctly As far as i can tell.

tested:
 - 16: da-one-black
 - 24: one-black

**Comment by SenchoPens** [comment]
Stylix users also confirm this fixes the issue, closing.
