### ISSUE TITLE
Schemes with dashes in the name don't work.

### ISSUE THREAD

**Issue by Lyndeno** [SenchoPens/base16.nix#2]
When doing:
```nix
cssScheme = builtins.readFile (config.scheme inputs.base16-waybar);
```
when
```nix
config.scheme = "${inputs.base16-schemes}/gruvbox-dark-hard.yaml";
```
I get an error like this:
```
error: builder for '/nix/store/dfm82w1faj8kb4pg67k4p6ak9arnlyx5-gruvbox-dark-hard.drv' failed with exit code 1;
       last 3 log lines:
       > building
       > installing
       > cp: target 'hard.css': No such file or directory
```
this started after 124820f

**Comment by Lyndeno** [comment]
Using ```nord.yaml``` works fine

**Comment by Lyndeno** [comment]
Upon further testing, it appears it is not the dashes in the filename, but something in the scheme name, in this case the original scheme name is ```"Gruvbox dark, hard"```. Changing it to ```"Gruvbox"``` allows the theme to work. Perhaps the comma and/or space is not working in the latest commits?

**Comment by SenchoPens** [comment]
Hi, thanks! It must be fixed now, the problem was that the slug was initialized from the schemes name, not from the path to the scheme.

**Comment by Lyndeno** [comment]
Thanks!
