### ISSUE TITLE
`escapeShellArg` breaks using paths as `template`

### ISSUE THREAD

**Issue by danth** [SenchoPens/base16.nix#7]
The following error message is written to file instead of the output.

```
Error: open /nix/store/syncbcpk5c9s0cl7cq203dhh2wab9kkz-source/stylix/palette.json.mustache: no such file or directory
```

It seems like running the path through `escapeShellArg` stops it being listed as an input to the derivation, so presumably the sandbox is hiding it. It definitely exists from my perspective.

The build succeeds when `escapeShellArg` is removed, however I can see why that might be necessary if the name contains spaces.

**Comment by SenchoPens** [comment]
Hi @danth, can you please try out the latest release?

**Comment by danth** [comment]
Seems to be working, thanks!
