### ISSUE TITLE
Support for Tinted Theming

### ISSUE THREAD

**Issue by Industrial** [SenchoPens/base16.nix#9]
Hello. I would like to use Tinted Theming (continuation of Base16) with this. I think the format changed a bit:
- https://github.com/tinted-theming/base16-schemes/blob/main/catppuccin-frappe.yaml (old)
- https://github.com/tinted-theming/schemes/blob/spec-0.11/base16/catppuccin-frappe.yaml (new)

**Comment by SenchoPens** [comment]
Hi, I've added support for this last month, can you update the library to the latest version and see if it works for you?
`nix flake lock --update-input base16-nix`

**Comment by SenchoPens** [comment]
Hi @Industrial, it works for me and also for ppl in the issue above, please reopen if it doesn't work for you or you require further help.

**Comment by Industrial** [comment]
Cool, I was using it via `stylix` so I'll try again. Thanks!
